import type { AdminAction, ChangeLogEntry } from "./types";

const MIN = 60_000;
const HOUR = 3_600_000;
const DAY = 86_400_000;

export function seedActions(): AdminAction[] {
  const now = Date.now();
  return [
    {
      id: "A-1",
      createdAt: now - 9 * MIN,
      actorId: "ad-1",
      actorName: "Dana Okonkwo",
      actionName: "Refund client order",
      service: "Orders",
      entity: "order · ord_10293",
      summary: "Refunded AED 450.00 for a duplicate charge on order ord_10293.",
      result: "success",
      severity: "warning",
      ticketType: "edr",
      ticketId: "EDR-2211",
      inputs: [
        { label: "Order", value: "ord_10293" },
        { label: "Amount", value: "AED 450.00" },
        { label: "Reason", value: "Duplicate charge" },
        { label: "Client", value: "j***@***.ae" },
      ],
    },
    {
      id: "A-2",
      createdAt: now - 42 * MIN,
      actorId: "ad-3",
      actorName: "Mara Devlin",
      actionName: "Suspend client account",
      service: "Clients and Profiles",
      entity: "client · cl_5521",
      summary: "Suspended client cl_5521 for 30 days after repeated no-shows.",
      result: "success",
      severity: "warning",
      ticketType: "tt",
      ticketId: "TT-1043",
      inputs: [
        { label: "Client", value: "cl_5521" },
        { label: "Duration", value: "30 days" },
        { label: "Reason", value: "Repeated no-shows" },
      ],
    },
    {
      id: "A-3",
      createdAt: now - 3 * HOUR,
      actorId: "ad-2",
      actorName: "Sam Al-Rashid",
      actionName: "Grant role to admin",
      service: "User Management",
      entity: "admin · ad-4",
      summary: "Granted “Refund supervisor” to Theo Nakamura with a 30-day expiry.",
      result: "success",
      severity: "info",
      ticketType: null,
      ticketId: null,
      inputs: [
        { label: "Admin", value: "Theo Nakamura" },
        { label: "Role", value: "Refund supervisor" },
        { label: "Expiry", value: "30 days" },
      ],
    },
    {
      id: "A-4",
      createdAt: now - 5 * HOUR,
      actorId: "ad-1",
      actorName: "Dana Okonkwo",
      actionName: "Update product price",
      service: "Products & Services",
      entity: "product · pkg_aba_12",
      summary: "Changed the monthly price of the ABA-12 package from AED 3,200 to AED 3,450.",
      result: "success",
      severity: "info",
      ticketType: null,
      ticketId: null,
      inputs: [
        { label: "Package", value: "pkg_aba_12" },
        { label: "Old price", value: "AED 3,200.00" },
        { label: "New price", value: "AED 3,450.00" },
      ],
    },
    {
      id: "A-5",
      createdAt: now - 8 * HOUR,
      actorId: "ad-2",
      actorName: "Sam Al-Rashid",
      actionName: "Delete admin account",
      service: "User Management",
      entity: "admin · ad_legacy_2",
      summary: "Permanently deleted a deactivated admin account and revoked all its grants.",
      result: "success",
      severity: "critical",
      ticketType: "edr",
      ticketId: "EDR-2247",
      inputs: [
        { label: "Admin", value: "ad_legacy_2" },
        { label: "Grants revoked", value: "3" },
        { label: "Reason", value: "Offboarding" },
      ],
    },
    {
      id: "A-6",
      createdAt: now - 26 * HOUR,
      actorId: "ad-4",
      actorName: "Theo Nakamura",
      actionName: "Reset client password",
      service: "Clients and Profiles",
      entity: "client · cl_4410",
      summary: "Sent a password reset link to the registered email for client cl_4410.",
      result: "success",
      severity: "info",
      ticketType: null,
      ticketId: null,
      inputs: [
        { label: "Client", value: "cl_4410" },
        { label: "Channel", value: "Email" },
      ],
    },
    {
      id: "A-7",
      createdAt: now - 30 * HOUR,
      actorId: "ad-4",
      actorName: "Theo Nakamura",
      actionName: "Refund client order",
      service: "Orders",
      entity: "order · ord_10188",
      summary: "Refund declined — the order was already fully refunded.",
      result: "failure",
      severity: "warning",
      ticketType: null,
      ticketId: null,
      inputs: [
        { label: "Order", value: "ord_10188" },
        { label: "Amount", value: "AED 900.00" },
      ],
    },
    {
      id: "A-8",
      createdAt: now - 2 * DAY,
      actorId: "ad-1",
      actorName: "Dana Okonkwo",
      actionName: "Export financial transactions",
      service: "Financial Transactions",
      entity: "report · fin_export",
      summary: "Exported 4,120 of 4,200 rows — 80 rows skipped by the date filter.",
      result: "partial",
      severity: "warning",
      ticketType: null,
      ticketId: null,
      inputs: [
        { label: "Range", value: "01-Jul-2026 → 31-Jul-2026" },
        { label: "Rows", value: "4,120" },
        { label: "Format", value: "CSV" },
      ],
    },
    {
      id: "A-9",
      createdAt: now - 3 * DAY,
      actorId: "ad-2",
      actorName: "Sam Al-Rashid",
      actionName: "Update security policy",
      service: "Security",
      entity: "policy · v4",
      summary: "Lowered the failed-login lockout threshold from 10 to 5 attempts.",
      result: "success",
      severity: "critical",
      ticketType: null,
      ticketId: null,
      inputs: [
        { label: "Setting", value: "Lockout threshold" },
        { label: "Old value", value: "10" },
        { label: "New value", value: "5" },
        { label: "Reason", value: "Tightening after audit" },
      ],
    },
    {
      id: "A-10",
      createdAt: now - 4 * DAY,
      actorId: "ad-1",
      actorName: "Dana Okonkwo",
      actionName: "Unlock admin account",
      service: "User Management",
      entity: "admin · ad-3",
      summary: "Unlocked Mara Devlin after identity was verified over the phone.",
      result: "success",
      severity: "info",
      ticketType: "tt",
      ticketId: "TT-1099",
      inputs: [
        { label: "Admin", value: "Mara Devlin" },
        { label: "Verified via", value: "Phone" },
      ],
    },
    {
      id: "A-11",
      createdAt: now - 6 * DAY,
      actorId: "ad-2",
      actorName: "Sam Al-Rashid",
      actionName: "Forfeit wallet balance",
      service: "Financial Transactions",
      entity: "wallet · wl_2288",
      summary: "Forfeited AED 120.00 of expired gift balance from wallet wl_2288.",
      result: "success",
      severity: "critical",
      ticketType: "tt",
      ticketId: "TT-1101",
      inputs: [
        { label: "Wallet", value: "wl_2288" },
        { label: "Amount", value: "AED 120.00" },
        { label: "Reason", value: "Expired gift balance" },
      ],
    },
    {
      id: "A-12",
      createdAt: now - 9 * DAY,
      actorId: "ad-3",
      actorName: "Mara Devlin",
      actionName: "Update remuneration level",
      service: "Specialists",
      entity: "specialist · sp_7781",
      summary: "Raised the per-session ABA rate for specialist sp_7781.",
      result: "success",
      severity: "info",
      ticketType: null,
      ticketId: null,
      inputs: [
        { label: "Specialist", value: "sp_7781" },
        { label: "Old rate", value: "AED 180.00" },
        { label: "New rate", value: "AED 200.00" },
      ],
    },
  ];
}

export function seedChanges(): ChangeLogEntry[] {
  const now = Date.now();
  return [
    {
      id: "C-1",
      createdAt: now - 9 * MIN,
      actionId: "A-1",
      actorName: "Dana Okonkwo",
      table: "orders",
      recordId: "ord_10293",
      operation: "update",
      changes: [
        { column: "status", before: "paid", after: "refunded" },
        { column: "refunded_amount", before: "0.00", after: "450.00" },
      ],
    },
    {
      id: "C-2",
      createdAt: now - 9 * MIN,
      actionId: "A-1",
      actorName: "Dana Okonkwo",
      table: "wallet_transactions",
      recordId: "wtx_88120",
      operation: "insert",
      changes: [
        { column: "type", before: null, after: "refund" },
        { column: "amount", before: null, after: "450.00" },
      ],
    },
    {
      id: "C-3",
      createdAt: now - 42 * MIN,
      actionId: "A-2",
      actorName: "Mara Devlin",
      table: "clients",
      recordId: "cl_5521",
      operation: "update",
      changes: [
        { column: "status", before: "active", after: "suspended" },
        { column: "suspended_until", before: null, after: "22-Sep-2026" },
      ],
    },
    {
      id: "C-4",
      createdAt: now - 3 * HOUR,
      actionId: "A-3",
      actorName: "Sam Al-Rashid",
      table: "role_grants",
      recordId: "grant_5",
      operation: "insert",
      changes: [
        { column: "admin_id", before: null, after: "ad-4" },
        { column: "role_id", before: null, after: "role-refund" },
        { column: "expires_at", before: null, after: "22-Sep-2026" },
      ],
    },
    {
      id: "C-5",
      createdAt: now - 5 * HOUR,
      actionId: "A-4",
      actorName: "Dana Okonkwo",
      table: "products",
      recordId: "pkg_aba_12",
      operation: "update",
      changes: [{ column: "monthly_price", before: "3200.00", after: "3450.00" }],
    },
    {
      id: "C-6",
      createdAt: now - 8 * HOUR,
      actionId: "A-5",
      actorName: "Sam Al-Rashid",
      table: "admin_accounts",
      recordId: "ad_legacy_2",
      operation: "delete",
      changes: [
        { column: "name", before: "Legacy Admin", after: null },
        { column: "email", before: "l***@***.ae", after: null },
        { column: "status", before: "deactivated", after: null },
      ],
    },
    {
      id: "C-7",
      createdAt: now - 26 * HOUR,
      actionId: "A-6",
      actorName: "Theo Nakamura",
      table: "clients",
      recordId: "cl_4410",
      operation: "update",
      changes: [{ column: "password_reset_token", before: null, after: "••••••" }],
    },
    {
      id: "C-8",
      createdAt: now - 3 * DAY,
      actionId: "A-9",
      actorName: "Sam Al-Rashid",
      table: "security_policies",
      recordId: "policy_v4",
      operation: "insert",
      changes: [
        { column: "lockout_threshold", before: null, after: "5" },
        { column: "effective_from", before: null, after: "20-Aug-2026" },
      ],
    },
    {
      id: "C-9",
      createdAt: now - 6 * DAY,
      actionId: "A-11",
      actorName: "Sam Al-Rashid",
      table: "wallets",
      recordId: "wl_2288",
      operation: "update",
      changes: [{ column: "gift_balance", before: "120.00", after: "0.00" }],
    },
    {
      id: "C-10",
      createdAt: now - 9 * DAY,
      actionId: "A-12",
      actorName: "Mara Devlin",
      table: "specialist_rates",
      recordId: "sp_7781",
      operation: "update",
      changes: [{ column: "aba_session_rate", before: "180.00", after: "200.00" }],
    },
    {
      id: "C-11",
      createdAt: now - 11 * DAY,
      actionId: null,
      actorName: "System",
      table: "sessions",
      recordId: "sess_expired_batch",
      operation: "delete",
      changes: [{ column: "expired", before: "true", after: null }],
    },
    {
      id: "C-12",
      createdAt: now - 12 * DAY,
      actionId: null,
      actorName: "Dana Okonkwo",
      table: "clients",
      recordId: "cl_3092",
      operation: "update",
      changes: [{ column: "primary_language", before: "en", after: "ar" }],
    },
  ];
}
